### ISSUE TITLE
Either libusb-1.0 not found or no such file or directory

### ISSUE THREAD

**Issue by tuckotb** [rp-rs/sample-project#2]
When I run ``cargo build --release`` it says:
```
error: failed to run custom build command for `rp2040-boot2 v0.1.2 (https://github.com/rp-rs/rp2040-boot2-rs?branch=main#dae42b2d)`

Caused by:
  process didn't exit successfully: `/root/sample-project/target/release/build/rp2040-boot2-61537f02950957d3/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'executing arm-none-eabi-gcc: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /root/.cargo/git/checkouts/rp2040-boot2-rs-b6d9ce848d516f57/dae42b2/build.rs:20:10
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
When I run ``cargo install --git https://github.com/rp-rs/probe-run --branch main`` It says:
```
error: failed to run custom build command for `hidapi v1.2.3`

Caused by:
  process didn't exit successfully: `/tmp/cargo-installmg5Xss/release/build/hidapi-b9b4d89bf2287c3c/build-script-build` (exit code: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBUSB_1.0_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=LIBUSB_1.0_STATIC
  cargo:rerun-if-env-changed=LIBUSB_1.0_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
  cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_PATH
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Unable to find libusb-1.0: "Failed to run `\"pkg-config\" \"--libs\" \"--cflags\" \"libusb-1.0\"`: No such file or directory (os error 2)"', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/hidapi-1.2.3/build.rs:65:60
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: failed to compile `probe-run-rp v0.1.9 (https://github.com/rp-rs/probe-run?branch=main#9ecd257b)`, intermediate artifacts can be found at `/tmp/cargo-installmg5Xss`

Caused by:
  build failed
```

**Comment by eolder** [comment]
What platform are you building on? It looks like you need to install `libusb`

**Comment by eolder** [comment]
Closing from inactivity.
